### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hasan1818666891** [TOR968/PitchTalkBot#2]
--- Start processing account 1 | proxy: null ---
Authorization successful! Token received for Ayanriya1.                       Farming...                                                                    Farming is not ready yet.                                                     Remaining: 5 hours, 28 minutes, 14 seconds.                                   Processing Tasks...                                                            ✅ COMPLETED: Follow PitchTalk on YouTube                                     🟡 VERIFYING: Share X Post                                                    🔴 NOT DONE: Subscribe to PitchTalk chanel
 🔴 NOT DONE: Join PitchTalk Chat
 ✅ COMPLETED: Follow PitchTalk on X
--- Executing task share-tiktok ---
API Error: {                                                                    message: 'Failed to create daily taskInternalServerErrorException: User does not have enough coins',                                                        error: 'Internal Server Error',                                               statusCode: 500                                                             }                                                                             Error processing account: AxiosError: Request failed with status code 500
    at settle (/data/data/com.termux/files/home/PitchTalkBot/node_modules/axios/dist/node/axios.cjs:2019:12)                                                    at IncomingMessage.handleStreamEnd (/data/data/com.termux/files/home/PitchTalkBot/node_modules/axios/dist/node/axios.cjs:3135:11)

**Comment by TOR968** [comment]
Did you do it, buddy?
![image](https://github.com/user-attachments/assets/2af1eaa1-f937-4df1-a373-89fe340a9f67)
